#file location
pretest_path: 'data/pretest.csv' #choose last 30 days pretest data
test_path: 'data/test.csv' 

# id level data, id is the unique identifier for each row
# metrics and columns
### required columns: conversion_metrics, id_column, date_column, group_column, control_group, treatment_group, binary
conversion_metric: 'converted' #eg. clicks, converted, sales, spend
id_column: 'impression_id' #eg. impression_id, user_id, id is the unique identifier for each row
date_column: 'date' #eg. date, day, if no date column
group_column: 'group' #eg. group, treatment column names
control_group: 0 #eg. 0, 1, or 'control', 'treatment'
treatment_group: 1 #eg. 0, 1, or 'control', 'treatment'
binary: True #True for proportion, False for mean

### optional columns: AB_metric, AA_metric, experiment_column, spend_column
AB_metric: 'landingpage_test' #row name for experiment group, if not specified, leave it blank
AA_metric: 'AA_test' #row name for experiment group, if not specified, leave it blank
experiment_column: 'experiment' #eg. experiment, experiment_group, if no experiment column, leave it blank
spend_column: 'spend' #eg. spend, cost, if no spend column, leave it blank


#--------------------------------------------------------------Input Parameters--------------------------------------------------------------
# keep the same as the default if not sure
# Power Analysis Input Parameters
MDE : 0.1 #Empirical threshold eg.10% lift or 5% lift
significance_level : 0.05 #Empirical threshold eg. 5% or 1%
power : 0.8 #Empirical threshold eg. 80% or 90%
group_ratio : 1 # 1 for 50/50, 2 for 2/1, 3 for 3/1, etc.

# AA Test Input Parameters
AA_alpha : 0.05 ##Empirical threshold eg. 5% or 1%

# Sample Ratio Mismatch Input Parameters
SRM_alpha : 0.05 ##Empirical threshold eg. 5% or 1%

# AB Test Input Parameters
AB_alpha : 0.05 #Empirical threshold eg. 5% or 1%

# Novelty Effect Input Parameters
NE_alpha : 0.05 #Empirical threshold eg. 5% or 1%